<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Gastón Ramos</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">

  <!--[if lte IE 8]>
    <link rel="stylesheet" href="http://purecss.io/combo/1.17.16?/css/main-grid-old-ie.css&/css/main-old-ie.css&/css/rainbow/baby-blue.css">
  <![endif]-->

  <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://purecss.io/combo/1.17.16?/css/main-grid.css&/css/main.css&/css/rainbow/baby-blue.css">
  <!--<![endif]-->
</head>

<body>

</body>
