<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Gastón Ramos</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">

  <!--[if lte IE 8]>
    <link rel="stylesheet" href="http://purecss.io/combo/1.17.16?/css/main-grid-old-ie.css&/css/main-old-ie.css&/css/rainbow/baby-blue.css">
  <![endif]-->

  <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://purecss.io/combo/1.17.16?/css/main-grid.css&/css/main.css&/css/rainbow/baby-blue.css">
  <!--<![endif]-->
</head>

<body>
  <div class="header">
    <h2>[ Gastón Ramos - Software Engineer ]</h2>
  </div>
  <div class="pure-menu pure-menu-open pure-menu-horizontal">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/music">Music</a></li>
      <li><a href="/work">Poftfolio</a></li>
      <li><a href="http://gastonramos.wordpress.com">Blog</a></li>
      <li><a href="/translations">Translations</a></li>
      <li><a href="/talks">Talks</a></li>
      <li><a href="/radio">Radio</a></li>
    </ul>
  </div>

</body>
